### PR TITLE
Add support for BrowserViews

### PR DESCRIPTION
**Pull request by gshahbazian**

### CODE REVIEW

**Comment by ibash** [comment]
@sindresorhus

**Comment by jrobeson** [comment]
Why is `win` renamed `window`?  I think such a change should be done separately if possible.

**Comment by jrobeson** [comment]
I'm retracting that, I see why.

**Comment by sindresorhus** [comment]
Friendly ping :)

**Comment by jsheffers** [comment]
Can you be more specific on what needs to be updated here?  I'd love to contribute as I need this functionality.

**Pull request closed without merging**
