### PR TITLE
Added Bing Search

### PR DESCRIPTION
**Pull request by jasonpatrickellykrause**

### CODE REVIEW

**Comment by sindresorhus** [comment]
I appreciate the pull request, but I don't intend to add more search engines. It's a slippery slope. Next, someone will want DDG, etc.

**Comment by sindresorhus** [comment]
I highly doubt Mattermost or Slack are using this package.

**Comment by Boojapho** [comment]
Mattermost uses this package: https://github.com/mattermost/desktop/blob/release-5.0/package.json#L132 and https://github.com/mattermost/desktop/blob/master/src/main/contextMenu.ts#L6

**Comment by vraravam** [comment]
I would love for the ability to use search engines other than Google. Is this something that's being worked upon?

**Pull request closed without merging**
